project:
  type: book
  output-dir: docs

book:
  title: "The Metastasis Book"
  author: "Matthew Feng"
  date: "6/1/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



